---
# Copyright 2022 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Set cacert mount if present
  block:
    - name: Determine if cacert file exists
      ansible.builtin.stat:
        path: "{{ edpm_ovn_controller_tls_cacert_bundle_src }}"
      register: cacert_bundle_exists

    - name: Set ca_cert mount
      ansible.builtin.set_fact:
        edpm_ovn_controller_tls_cacert_volumes:
          - "{{ edpm_ovn_controller_tls_cacert_bundle_src }}:{{ edpm_ovn_controller_tls_cacert_bundle_dest }}:ro,z"
      when: cacert_bundle_exists.stat.exists

- name: Ensure /usr/libexec/edpm-start-podman-container exists
  ansible.builtin.import_role:
    name: edpm_container_manage
    tasks_from: shutdown.yml

- name: Run ovn_controller container
  ansible.builtin.include_role:
    name: osp.edpm.edpm_container_standalone
  vars:
    edpm_container_standalone_service: ovn_controller
    edpm_container_standalone_container_defs:
      ovn_controller: "{{ lookup('template', 'ovn_controller.yaml.j2') | from_yaml }}"
    edpm_container_standalone_kolla_config_files:
      ovn_controller: "{{ lookup('template', 'kolla_ovn_controller.yaml.j2') | from_yaml }}"
  when: not edpm_use_bootc

- name: Configure ovn_controller for bootc deployments
  block:
  - name: Collect default pod spec
    ansible.builtin.slurp:
      src: /usr/share/containers/systemd/ovn_controller.yaml
    register: ovn_controller_pod_spec

  - name: Decode and parse the YAML content
    ansible.builtin.set_fact:
      ovn_controller_pod_spec: "{{ ovn_controller_pod_spec.content | b64decode | from_yaml }}"

  - name: Update fields in the YAML data
    ansible.builtin.set_fact:
      updated_pod_spec: >-
        {{
          ovn_controller_pod_spec | combine({
            'spec': {
              'containers': ovn_controller_pod_spec.spec.containers | zip_longest([], [{'image': edpm_ovn_controller_agent_image}]) | map('combine') | list,
               },
            }, recursive=true)
        }}

  - name: Write the updated pod spec to /etc
    ansible.builtin.copy:
      content: "{{ updated_pod_spec | to_yaml }}"
      dest: /etc/containers/systemd/ovn_controller.yaml
      mode: '0644'

  - name: Copy systemd service template
    ansible.builtin.copy:
      remote_src: true
      src: /usr/share/containers/systemd/edpm-compute@.kube
      dest: /etc/containers/systemd/edpm-compute@.kube

  - name: Update service template Yaml path
    ansible.builtin.ini_file:
      path: /etc/containers/systemd/edpm-compute@.kube
      section: Kube
      option: "Yaml"
      value: "/etc/containers/systemd/%i.yaml"
      mode: "0644"

  - name: Run ovn_controller container
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: edpm-compute@ovn_controller
      state: started
  become: true
  when: edpm_use_bootc
