#!/bin/sh

# Copyright 2024 Inc.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

URL="http://0.0.0.0:8888/healthz"
TIMEOUT=5 # Timeout in seconds

# Get the HTTP status code and response body using curl
RESPONSE=$(curl -s -w "%{http_code}" $URL --max-time $TIMEOUT)
BODY=${RESPONSE:0:-3}  # Extract the body (all but the last 3 characters)
HTTP_CODE=${RESPONSE: -3}  # Extract the last 3 characters as the HTTP status code

# Check the HTTP status code
if [ "$HTTP_CODE" -ne 200 ]; then
    echo "$1 Health check failed: HTTP status code $HTTP_CODE"
    exit 1
fi

# Check if the response body contains "ok"
if [[ "$BODY" != *"ok"* ]]; then
    echo "$1 Health check failed: Response body does not contain 'ok'"
    exit 1
fi

echo "$1 Health check passed: HTTP status code $HTTP_CODE, Health response 'ok'"
exit 0
