#!/bin/sh

# Copyright 2024 Inc.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

URL="http://0.0.0.0:8888"

# Get the HTTP status code using curl
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $URL)

# If the HTTP status code is not 200, exit with a non-zero code
if [ "$HTTP_CODE" -ne 200 ]; then
          echo "$1 Health check failed: HTTP status code $HTTP_CODE"
            exit 1
fi

echo "$1 Health check passed: HTTP status code $HTTP_CODE"
exit 0
