---
- name: Configure sidecar containers scripts
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ edpm_neutron_ovn_agent_lib_dir }}/{{ item.dest }}"
    setype: "container_file_t"
    mode: "0755"
  loop:
    - {"src": "wrappers/haproxy.j2", "dest": "ovn_agent_haproxy_wrapper"}

- name: Configure kill_scripts for sidecar containers
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ edpm_neutron_ovn_agent_lib_dir }}/kill_scripts/{{ item.dest }}"
    setype: "container_file_t"
    mode: "0755"
  loop:
    - {"src": "wrappers/kill-script.j2", "dest": "haproxy-kill"}
