---
- name: Converge
  hosts: all
  roles:
    - role: "edpm_accel_drivers"
      vars:
        edpm_accel_drivers:
          features:
            nvidia_mig:
              manage: true
              geometries:
                - "14,14,14,14"
                - "2g.12gb,2g.12gb"
