---

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    test_helper_dir: "../../../../molecule/test-helpers"
    edpm_cyborg_tls_ca_src_dir: /tmp/pki
    edpm_cyborg_config_dest: /var/lib/openstack/cyborg
  tasks:
    - name: ensure expected directories exist
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_dir.yaml"
      loop:
        - "/var/lib/openstack"
        - "{{ edpm_cyborg_config_dest }}"
        - "/var/lib/cyborg"
        - "/etc/nvme"
        - "{{ edpm_cyborg_tls_ca_src_dir }}"

    - name: ensure extra mounts are present
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_mounts.yaml"
      loop:
        - {"name": "cyborg_agent", "src": "/var/lib/test_accel_device",
            "dest": "/var/lib/test_accel_device", "options": "rw"}

    - name: ensure cyborg config mounts are present
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_mounts.yaml"
      loop:
        - name: "cyborg_agent"
          src: "{{ edpm_cyborg_config_dest }}"
          dest: "/var/lib/kolla/config_files/src"
          options: "ro"

    - name: ensure cyborg agent container has /dev mounted
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_mounts.yaml"
      loop:
        - {"name": "cyborg_agent", "src": "/dev", "dest": "/dev", "options": ""}

    - name: ensure cyborg agent container has /sys mounted
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_mounts.yaml"
      loop:
        - {"name": "cyborg_agent", "src": "/sys", "dest": "/sys", "options": ""}

    - name: ensure TLS CA bundle is mounted in container
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_mounts.yaml"
      loop:
        - name: "cyborg_agent"
          src: "{{ edpm_cyborg_tls_ca_src_dir }}/tls-ca-bundle.pem"
          dest: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
          options: "ro"

    - name: ensure systemd services are defined
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_systemd_unit.yaml"
      loop:
        - {"name": "edpm_cyborg_agent.service", "running": false}

    - name: ensure podman container exists
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_podman.yaml"
      loop:
        - {"name": "cyborg_agent", "running": false}

    - name: Check if cyborg user exists
      ansible.builtin.getent:
        database: passwd
        key: cyborg
      register: cyborg_user

    - name: Assert that cyborg user is created with kolla uid and gid
      ansible.builtin.assert:
        that:
          - "cyborg_user.ansible_facts.getent_passwd.cyborg[1] == '42592'"
          - "cyborg_user.ansible_facts.getent_passwd.cyborg[2] == '42592'"

    - name: Check if after sync old file is removed
      ansible.builtin.stat:
        path: '/var/lib/openstack/cyborg/test.conf'
      register: cyborg_old_test_conf

    - name: Assert that stale config file was removed by sync
      ansible.builtin.assert:
        that:
          - "not cyborg_old_test_conf.stat.exists"

    - name: Verify cyborg config was synced
      ansible.builtin.stat:
        path: "{{ edpm_cyborg_config_dest }}/01-cyborg.conf"
      register: cyborg_conf

    - name: Assert cyborg config exists
      ansible.builtin.assert:
        that:
          - cyborg_conf.stat.exists
