---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify NVIDIA repository metadata was cached
      ansible.builtin.find:
        paths: /var/cache/dnf
        patterns: 'nvidia_gpu*'
        file_type: directory
      register: nvidia_dnf_cache
      failed_when: nvidia_dnf_cache.files | length < 1

    - name: Verify AMD mock driver was downloaded
      ansible.builtin.stat:
        path: /var/cache/accel-drivers/mock-amd-driver.rpm
      register: amd_package
      failed_when: not amd_package.stat.exists
