#!/bin/bash
# Cleanup neutron OVS bridges. To be called on startup to avoid
# "difficult-to-debug" issues with partially configured resources.

$INT_BRIDGE=${INT_BRIDGE:-"br-int"}
$TUN_BRIDGE=${TUN_BRIDGE:-"br-tun"}

for port in `ovs-vsctl list-ports ${INT_BRIDGE}`; do
    skip_cleanup=`ovs-vsctl --if-exists get Interface $port external_ids:skip_cleanup`
    if ! [[ "x$skip_cleanup" == "x\"true\"" ]]; then
        ovs-vsctl del-port ${INT_BRIDGE} $port
    fi
done

ovs-vsctl --if-exists del-br ${TUN_BRIDGE}

# Clean up trunk port bridges
for br in $(ovs-vsctl list-br | egrep 'tbr-[0-9a-f\-]+'); do
    ovs-vsctl --if-exists del-br $br
done
