---
- name: Converge with full geometry list (two GPUs)
  hosts: all
  roles:
    - role: "edpm_accel_drivers"
      vars:
        edpm_accel_drivers:
          features:
            nvidia_mig:
              manage: true
              geometries:
                - "14,14,14,14"
                - "2g.12gb,2g.12gb"

- name: Converge with reduced geometry list (one GPU) to trigger cleanup
  hosts: all
  roles:
    - role: "edpm_accel_drivers"
      vars:
        edpm_accel_drivers:
          features:
            nvidia_mig:
              manage: true
              geometries:
                - "14,14,14,14"
