---
edpm_accel_drivers:
  cache_dir: "/var/cache/accel-drivers"
  cleanup_temp_files: true
  download:
    delay: "{{ edpm_download_delay | default(60) }}"
    retries: "{{ edpm_download_retries | default(5) }}"
  vendors:
    nvidia_gpu:
      enabled: false
      denylist_modules:
        - nouveau
      repo:
        url: ""
        gpgkey: ""
        module_name: "nvidia-driver"
        module_stream: "latest"
        package_name: "nvidia-driver"
        disable_gpg_check: false
        no_basearch: false
      custom_url:
        url: ""
        ssl_no_verify: false
        disable_gpg_check: false
    amd_gpu:
      enabled: false
      denylist_modules:
        - amdgpu
      repo:
        url: ""
        gpgkey: ""
        module_name: ""
        module_stream: ""
        package_name: ""
        disable_gpg_check: false
        no_basearch: false
      custom_url:
        url: ""
        ssl_no_verify: false
        disable_gpg_check: false
  kernel:
    pin: false
    version: ""
    remove_old: true
  reboot:
    post_driver: false
    timeout: 1800
    wait_for_connection_timeout: 900
    verify_vgpu_mgr: true
  features:
    nvidia_mig:
      manage: false
      geometries: []
