---

- name: Remove GPU module if loaded
  become: true
  ansible.builtin.command: modprobe -r {{ module_name }}
  changed_when: false

- name: Blacklist GPU module
  become: true
  ansible.builtin.copy:
    content: |
      blacklist {{ module_name }}
    dest: /etc/modprobe.d/blacklist-{{ module_name }}.conf
    mode: "0644"
