---

- name: Setup configuration and build enabled vendors list
  ansible.builtin.import_tasks: setup_config.yml

- name: Download GPU drivers for enabled vendors
  ansible.builtin.include_tasks: download_driver.yml
  loop: "{{ _edpm_accel_drivers_enabled_vendors }}"
  loop_control:
    loop_var: vendor_name
