---

- name: Install driver package for {{ vendor_name }}
  become: true
  ansible.builtin.dnf:
    name: "{{ _edpm_accel_drivers_package }}"
    state: present
    disable_gpg_check: "{{ _edpm_accel_drivers_disable_gpg_check }}"
    download_only: "{{ _edpm_accel_drivers_download_only | default(false) }}"
  register: _edpm_accel_drivers_install_packages_result
  until: _edpm_accel_drivers_install_packages_result is succeeded
  retries: "{{ _edpm_accel_drivers_config.download.retries }}"
  delay: "{{ _edpm_accel_drivers_config.download.delay }}"
