---

- name: Fail when using image mode
  ansible.builtin.debug:
    msg: edpm_accel_drivers role not supported with bootc/image mode
  when: ansible_local.bootc is defined and ansible_local.bootc
  failed_when: true

- name: Setup configuration and build enabled vendors list
  ansible.builtin.import_tasks: setup_config.yml

- name: Install GPU drivers for enabled vendors
  ansible.builtin.include_tasks: driver_install.yml
  loop: "{{ _edpm_accel_drivers_enabled_vendors }}"
  loop_control:
    loop_var: vendor_name

- name: Clean up temporary directory
  when: _edpm_accel_drivers_config.cleanup_temp_files | bool
  become: true
  ansible.builtin.file:
    path: "{{ _edpm_accel_drivers_config.cache_dir }}"
    state: absent

- name: Run boot configuration tasks
  when: _edpm_accel_drivers_enabled_vendors | length > 0
  ansible.builtin.import_tasks: boot_config.yml

- name: Configure MIG partitioning on NVIDIA GPU
  when: _edpm_accel_drivers_config.features.nvidia_mig.manage | bool
  ansible.builtin.import_tasks: nvidia_mig_partitioning.yml
