---
- name: Install systemd unit to apply MIG layout for GPU {{ _edpm_accel_drivers_nvidia_mig_gpu_index }}
  become: true
  ansible.builtin.template:
    src: edpm_nvidia_mig_apply.service.j2
    dest: "/etc/systemd/system/edpm_nvidia_mig_apply_{{ _edpm_accel_drivers_nvidia_mig_gpu_index }}.service"
    mode: '0644'
  register: _edpm_accel_drivers_nvidia_mig_unit_installed
  vars:
    index: "{{ _edpm_accel_drivers_nvidia_mig_gpu_index }}"
    geometry: "{{ _edpm_accel_drivers_nvidia_mig_geometry }}"
    bdf: "{{ _edpm_accel_drivers_nvidia_mig_bdf_sriov }}"

- name: Disable (trigger only) edpm_nvidia_mig_apply service for GPU {{ _edpm_accel_drivers_nvidia_mig_gpu_index }}
  become: true
  ansible.builtin.systemd:
    name: "edpm_nvidia_mig_apply_{{ _edpm_accel_drivers_nvidia_mig_gpu_index }}.service"
    enabled: false
    masked: false
    daemon_reload: "{{ _edpm_accel_drivers_nvidia_mig_unit_installed.changed | default(false) | bool }}"

- name: Install systemd unit to cause MIG apply to run when 1st VF appears
  become: true
  register: _edpm_accel_drivers_nvidia_mig_apply_path_installed
  ansible.builtin.template:
    src: edpm_nvidia_mig_apply.path.j2
    dest: "/etc/systemd/system/edpm_nvidia_mig_apply_{{ _edpm_accel_drivers_nvidia_mig_gpu_index }}.path"
    mode: '0644'
  vars:
    bdf: "{{ _edpm_accel_drivers_nvidia_mig_bdf_sriov }}"
    vf0_bdf: "{{ _edpm_accel_drivers_nvidia_mig_vf0_bdf }}"

- name: Enable edpm_nvidia_mig_apply path activation for GPU {{ _edpm_accel_drivers_nvidia_mig_gpu_index }}
  become: true
  ansible.builtin.systemd:
    name: "edpm_nvidia_mig_apply_{{ _edpm_accel_drivers_nvidia_mig_gpu_index }}.path"
    enabled: true
    masked: false
    daemon_reload: "{{ _edpm_accel_drivers_nvidia_mig_apply_path_installed.changed | default(false) | bool }}"

- name: Ensure no MIG compute instances are in use before reconfiguring GPU {{ _edpm_accel_drivers_nvidia_mig_gpu_index }}
  ansible.builtin.include_tasks: nvidia_mig_partitioning_check_gpu_in_use.yml
  vars:
    _edpm_accel_drivers_nvidia_mig_check_gpu_index: "{{ _edpm_accel_drivers_nvidia_mig_gpu_index }}"

- name: Reset MIG mode before applying new layout
  when: _edpm_accel_drivers_nvidia_mig_unit_installed.changed | bool
  become: true
  ansible.builtin.command:
    cmd: nvidia-smi -i {{ _edpm_accel_drivers_nvidia_mig_gpu_index }} -mig 0
  changed_when: true

- name: Restart edpm_nvidia_mig_apply service to apply layout edpm service install time
  become: true
  ansible.builtin.systemd:
    name: "edpm_nvidia_mig_apply_{{ _edpm_accel_drivers_nvidia_mig_gpu_index }}.service"
    state: restarted
