---

# NOTE: Requires _edpm_accel_drivers_dkms_packages to be set by download_from_custom_url.yml
# NOTE: Compiling on the host is not supported, but it enables testing vGPU drivers on CS9 nodes
- name: Install DKMS build dependencies (UNSUPPORTED)
  vars:
    _edpm_accel_drivers_package: "{{ _edpm_accel_drivers_dkms_packages }}"
    _edpm_accel_drivers_disable_gpg_check: false
  ansible.builtin.include_tasks: install_from_rpm.yml

- name: Execute .run file (UNSUPPORTED)
  become: true
  ansible.builtin.command: "{{ _edpm_accel_drivers_temp_path }} --no-dkms --no-disable-nouveau --silent"
  args:
    creates: /usr/bin/nvidia-smi
