---
- name: Reboot node to load drivers and initialize vGPU manager
  become: true
  ansible.builtin.reboot:
    reboot_timeout: "{{ _edpm_accel_drivers_config.reboot.timeout }}"

- name: Wait for node to become reachable
  ansible.builtin.wait_for_connection:
    timeout: "{{ _edpm_accel_drivers_config.reboot.wait_for_connection_timeout }}"

- name: Verify nvidia-vgpu-mgr service started
  when: _edpm_accel_drivers_config.reboot.verify_vgpu_mgr | bool
  become: true
  ansible.builtin.systemd:
    name: nvidia-vgpu-mgr
    state: started
  register: _edpm_accel_drivers_vgpu_mgr_status
  until: _edpm_accel_drivers_vgpu_mgr_status is succeeded
  retries: 5
  delay: 10
