---
# Copyright 2025 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: "Ensure directory exists: {{ edpm_container_quadlet_kolla_config_dir }}"
  become: true
  ansible.builtin.file:
    path: "{{ edpm_container_quadlet_kolla_config_dir }}"
    state: directory
    recurse: true
    setype: container_file_t

- name: Create kolla config files
  become: true
  ansible.builtin.copy:
    content: "{{ item.value | to_nice_json }}"
    dest: "{{ edpm_container_quadlet_kolla_config_dir ~ '/' ~ item.key ~ '.json' }}"
    mode: "0600"
  loop: "{{ edpm_container_quadlet_kolla_config_files | dict2items }}"

- name: "Render Pod YAML for kube quadlet: {{ edpm_container_quadlet_service }}.yaml"
  become: true
  ansible.builtin.template:
    src: "service-quadlet-pod.yaml.j2"
    dest: "{{ edpm_container_quadlet_systemd_config_dir }}/{{ edpm_container_quadlet_service }}.yaml"
    mode: "0644"
  when: edpm_container_quadlet_type == 'kube'
  no_log: true

- name: "Render quadlet file: edpm@{{ edpm_container_quadlet_service }}.{{ edpm_container_quadlet_type }}"
  become: true
  ansible.builtin.template:
    src: "service-quadlet.{{ edpm_container_quadlet_type }}.j2"
    dest: "{{ edpm_container_quadlet_systemd_config_dir }}/edpm@{{ edpm_container_quadlet_service }}.{{ edpm_container_quadlet_type }}"
    mode: "0644"
  no_log: true

- name: "Start quadlet service edpm@{{ edpm_container_quadlet_service }}"
  ansible.builtin.systemd_service:
    name: "edpm@{{ edpm_container_quadlet_service }}"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
  when: not (edpm_container_quadlet_skip_start | default(false) | bool)
