
{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN curl -o /etc/yum.repos.d/delorean.repo https://trunk.rdoproject.org/centos9-antelope/current/delorean.repo && \
    curl -o /etc/yum.repos.d/delorean-deps.repo https://trunk.rdoproject.org/centos9-antelope/delorean-deps.repo && \
    dnf -y install sudo python3-libselinux selinux-policy {{ item.pkg_extras | default('') }} && \
    dnf clean all -y

CMD [ '/sbin/init' ]
