---
edpm_container_quadlet_kolla_config_dir: /var/lib/kolla/config_files
edpm_container_quadlet_systemd_config_dir: "/etc/containers/systemd"
edpm_container_quadlet_type: container
edpm_container_quadlet_service: ""
edpm_container_quadlet_service_image: ""
edpm_container_quadlet_service_volumes: []
edpm_container_quadlet_service_use_host_network: false
edpm_container_quadlet_service_privileged: true
edpm_container_quadlet_service_environment: {}
edpm_container_quadlet_service_healthcheck_cmd: ""
edpm_container_quadlet_service_after: []
edpm_container_quadlet_service_wants: []
edpm_container_quadlet_skip_start: false

edpm_container_quadlet_config_vol_prefix: /var/lib/openstack

edpm_container_quadlet_common_volumes:
  - /etc/hosts:/etc/hosts:ro
  - /etc/localtime:/etc/localtime:ro
  - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
  - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
  - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
  - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
  - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
  - /dev/log:/dev/log

edpm_container_quadlet_internal_tls_volumes:
  - /etc/pki/tls/certs/httpd:/etc/pki/tls/certs/httpd:ro
  - /etc/pki/tls/private/httpd:/etc/pki/tls/private/httpd:ro
