---
- name: Converge
  hosts: all
  roles:
    - role: "edpm_accel_drivers"
      vars:
        edpm_accel_drivers:
          vendors:
            nvidia_gpu:
              enabled: true
              custom_url:
                url: "file:///tmp/mock-nvidia-driver.run"
