FROM quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest

# Override Red Hat labels with Cisco-specific ones
LABEL name="openstack-aci-edpm-runner-ciscoaci"       vendor="Cisco Systems"       version="18.0.14"       release="1"       summary="This is Ciscoaci EDPM runnrr"       description="This will not be deployed"       maintainer="Cisco Systems"       com.redhat.component=""       com.redhat.license_terms=""       io.k8s.description="Cisco ACI EDPM runner for OpenStack"       io.k8s.display-name="Cisco ACI EDPM Runner"       url="https://www.cisco.com"

# Create licenses directory and add license file
RUN mkdir -p /licenses
COPY ./osp18/LICENSE.txt /licenses/LICENSE.txt

COPY ./roles/edpm_lldp /usr/share/ansible/roles/edpm_lldp
COPY ./roles/edpm_neutron_opflex_agent /usr/share/ansible/roles/edpm_neutron_opflex_agent
COPY ./roles/edpm_cisco_opflex_agent /usr/share/ansible/roles/edpm_cisco_opflex_agent
COPY ./playbooks/lldp.yml /usr/share/ansible/collections/ansible_collections/osp/edpm/playbooks/
COPY ./playbooks/neutron_opflex_agent.yml /usr/share/ansible/collections/ansible_collections/osp/edpm/playbooks/
COPY ./playbooks/opflex_agent.yml /usr/share/ansible/collections/ansible_collections/osp/edpm/playbooks/