---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    neutron_ovn_agent_conf: /var/lib/openstack/neutron-ovn-agent/01-neutron-ovn-agent.conf
  tasks:
    - name: Slurp neutron-ovn-agent config
      become: true
      ansible.builtin.slurp:
        src: "{{ neutron_ovn_agent_conf }}"
      register: agent_config

    - name: Assert [ovn_evpn] section is present with expected values
      ansible.builtin.assert:
        that:
          - "'[ovn_evpn]' in agent_config.content | b64decode"
          - "'bgp_as = 64999' in agent_config.content | b64decode"
          - "'bgp_local_interface = eth0' in agent_config.content | b64decode"
          - "'child_vxlan_port = 49152' in agent_config.content | b64decode"
          - "'extensions = ovn-evpn' in agent_config.content | b64decode"
