---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify neutron-bgp-peer-bridges
      ansible.builtin.shell: >
        /usr/bin/ovs-vsctl get open_vswitch . external_ids:neutron-bgp-peer-bridges
      register: output
      failed_when: output.stdout != 'br-peer1'

    - name: Verify neutron-bgp-interconnect-bridge override
      ansible.builtin.shell: >
        /usr/bin/ovs-vsctl get open_vswitch . external_ids:neutron-bgp-interconnect-bridge
      register: output
      failed_when: output.stdout != 'br-custom'
