name: Build and install collection
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
jobs:
  verify-collection:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
      with:
        python-version: '3.14'
    - name: Install ansible
      run: pip install ansible
    - name: Build ansible collection
      run: ansible-galaxy collection build .
    - name: Install collection
      run: ansible-galaxy collection install --force osp-edpm-*.tar.gz
